//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockExchangeClient.StockExchangeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StockExchangeService.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name ticker from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStockPrice", ReplyAction="*")]
        StockExchangeClient.StockExchangeService.GetStockPriceResponse GetStockPrice(StockExchangeClient.StockExchangeService.GetStockPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStockPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<StockExchangeClient.StockExchangeService.GetStockPriceResponse> GetStockPriceAsync(StockExchangeClient.StockExchangeService.GetStockPriceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStockPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStockPrice", Namespace="http://tempuri.org/", Order=0)]
        public StockExchangeClient.StockExchangeService.GetStockPriceRequestBody Body;
        
        public GetStockPriceRequest() {
        }
        
        public GetStockPriceRequest(StockExchangeClient.StockExchangeService.GetStockPriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStockPriceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ticker;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string user;
        
        public GetStockPriceRequestBody() {
        }
        
        public GetStockPriceRequestBody(string ticker, string user) {
            this.ticker = ticker;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStockPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStockPriceResponse", Namespace="http://tempuri.org/", Order=0)]
        public StockExchangeClient.StockExchangeService.GetStockPriceResponseBody Body;
        
        public GetStockPriceResponse() {
        }
        
        public GetStockPriceResponse(StockExchangeClient.StockExchangeService.GetStockPriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStockPriceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetStockPriceResult;
        
        public GetStockPriceResponseBody() {
        }
        
        public GetStockPriceResponseBody(int GetStockPriceResult) {
            this.GetStockPriceResult = GetStockPriceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : StockExchangeClient.StockExchangeService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<StockExchangeClient.StockExchangeService.ServiceSoap>, StockExchangeClient.StockExchangeService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StockExchangeClient.StockExchangeService.GetStockPriceResponse StockExchangeClient.StockExchangeService.ServiceSoap.GetStockPrice(StockExchangeClient.StockExchangeService.GetStockPriceRequest request) {
            return base.Channel.GetStockPrice(request);
        }
        
        public int GetStockPrice(string ticker, string user) {
            StockExchangeClient.StockExchangeService.GetStockPriceRequest inValue = new StockExchangeClient.StockExchangeService.GetStockPriceRequest();
            inValue.Body = new StockExchangeClient.StockExchangeService.GetStockPriceRequestBody();
            inValue.Body.ticker = ticker;
            inValue.Body.user = user;
            StockExchangeClient.StockExchangeService.GetStockPriceResponse retVal = ((StockExchangeClient.StockExchangeService.ServiceSoap)(this)).GetStockPrice(inValue);
            return retVal.Body.GetStockPriceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StockExchangeClient.StockExchangeService.GetStockPriceResponse> StockExchangeClient.StockExchangeService.ServiceSoap.GetStockPriceAsync(StockExchangeClient.StockExchangeService.GetStockPriceRequest request) {
            return base.Channel.GetStockPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<StockExchangeClient.StockExchangeService.GetStockPriceResponse> GetStockPriceAsync(string ticker, string user) {
            StockExchangeClient.StockExchangeService.GetStockPriceRequest inValue = new StockExchangeClient.StockExchangeService.GetStockPriceRequest();
            inValue.Body = new StockExchangeClient.StockExchangeService.GetStockPriceRequestBody();
            inValue.Body.ticker = ticker;
            inValue.Body.user = user;
            return ((StockExchangeClient.StockExchangeService.ServiceSoap)(this)).GetStockPriceAsync(inValue);
        }
    }
}
